#= require ./adapter
#= require_tree ./models
#= require_tree ./controllers
#= require_tree ./helpers
#= require_tree ./templates
#= require_tree ./initializers
#= require_tree ./routes
#= require ./router
#= require_self
